apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "portfolio-app.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "portfolio-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "portfolio-app.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
